import type { ApiEndpointDoc } from './api-catalog';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? '';

// Default headers iOS will send to Supabase REST/RPC.
// - apikey: your anon key
// - Authorization: Bearer <access_token> (user session)
const supabaseAuthHeaders = {
  apikey: SUPABASE_ANON_KEY,
  Authorization: 'Bearer <AUTH_TOKEN>',
  'Content-Type': 'application/json',
};

// Headers for Next.js API Routes (no apikey needed, same origin)
const nextApiHeaders = {
  Authorization: 'Bearer <AUTH_TOKEN>',
  'Content-Type': 'application/json',
};

export const iosApiCatalog: ApiEndpointDoc[] = [
  {
    id: 'ios.users.get',
    audience: 'ios',
    method: 'GET',
    path: '/api/ios/users/<userid>',
    summary: 'Get user profile',
    description:
      'Fetch a user profile by their UUID. If the user does not exist (e.g. deleted), returns an "Unknown user" placeholder object with the same shape.',
    auth: {
      type: 'bearer',
      notes: 'Send the Supabase Access Token in Authorization header.',
    },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    responseExample: {
      userid: '<user_uuid>',
      username: 'Alice',
      age: 28,
      gender: 'Female',
      personality: 'Funny',
      zipcode: '90210',
      phone: '+15555555555',
      bio: 'Hello world',
      education: 'College',
      profession: 'Engineer',
      avatar: 'https://example.com/avatar.jpg',
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
      is_digital_human: false,
    },
    notes: [
      'Not-found behavior: returns 200 with `{ username: "Unknown user", ... }` (placeholder user object).',
    ],
  },
  {
    id: 'ios.users.update.patch',
    audience: 'ios',
    method: 'PATCH',
    path: '/api/ios/users/<userid>',
    summary: 'Update my profile',
    description:
      'Update fields for the authenticated user. <userid> must match the token subject.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {
      username: 'Alice',
      profession: 'iOS Engineer',
      zipcode: '90210',
      avatar: 'https://example.com/my-new-avatar.jpg',
    },
    responseExample: {
      userid: '<user_uuid>',
      username: 'Alice',
      // ... other fields
    },
  },
  {
    id: 'ios.users.delete.soft',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/me/delete',
    summary: 'Delete my account',
    description:
      'Deletes the authenticated Supabase Auth user (hard delete). Database rows are removed via FK cascade. Storage cleanup is best-effort.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {},
    responseExample: { success: true },
  },
  {
    id: 'ios.auth.logout',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/me/logout',
    summary: 'Logout (cleanup push token)',
    description:
      "Deletes this device's push token for the authenticated user so the device stops receiving notifications after logout. Client should also clear local session.",
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: { token: '<fcm_token>', platform: 'ios' },
    responseExample: { success: true },
  },
  {
    id: 'ios.subscription.entitlement',
    audience: 'ios',
    method: 'GET',
    path: '/api/ios/me/entitlement',
    summary: 'Remaining swipes/messages + active plan',
    description:
      'Resolves entitlement from the active `subscription` + `subscription_catalog`, counts today’s `swipe` rows and `messages` sent by the user (UTC day). With no active subscription, quotas come from the `subscription_catalog` row whose `apple_product_id` matches env `FREE_TIER_APPLE_PRODUCT_ID` or the default `amber.subscription.free`. If that row is missing, env `FREE_TIER_SWIPES_PER_DAY` / `FREE_TIER_MESSAGES_PER_DAY` apply (defaults 20 / 20).',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {},
    responseExample: {
      remaining_swipes: 12,
      remaining_messages: 40,
      subscription: {
        id: '<subscription_uuid>',
        status: 'ACTIVE',
        current_period_end: '2026-05-01T00:00:00Z',
        plan: {
          id: '<catalog_uuid>',
          name: 'Premium Monthly',
          apple_product_id: 'com.example.premium.monthly',
        },
      },
    },
    notes: [
      '`remaining_messages` is `null` when the plan’s `messages_per_day` is null (unlimited).',
      'Counts are quota minus today’s usage (UTC day); see docs/subscription-design.md.',
    ],
  },
  {
    id: 'ios.subscription.catalog.read',
    audience: 'ios',
    method: 'GET',
    path: '/rest/v1/subscription_catalog',
    summary: 'Read subscription plan catalog (Supabase)',
    description:
      'Returns rows from `subscription_catalog` (plan definitions and App Store product ids). Used by the app to resolve `subscription_catalog_id` before POST purchase-intent. RLS: authenticated users may select.',
    auth: {
      type: 'bearer',
      notes: 'Use Supabase anon key + user access token (same as other REST calls).',
    },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    params: [
      {
        name: 'select',
        in: 'query',
        required: false,
        description: 'PostgREST column selection.',
        example: 'id,apple_product_id,name,billing_period,swipes_per_day,messages_per_day,price_cents,currency',
      },
      {
        name: 'apple_product_id',
        in: 'query',
        required: false,
        description: 'Filter to one product, e.g. `eq.amber.premium.monthly.0.0`.',
        example: 'eq.amber.premium.monthly.0.0',
      },
      {
        name: 'limit',
        in: 'query',
        required: false,
        example: '10',
      },
    ],
    requestExample: {},
    responseExample: [
      {
        id: '<catalog_uuid>',
        apple_product_id: 'amber.premium.monthly.0.0',
        name: 'Premium Monthly',
        billing_period: 'monthly',
        swipes_per_day: 60,
        messages_per_day: null,
        price_cents: 999,
        currency: 'USD',
      },
    ],
  },
  {
    id: 'ios.subscription.swipe',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/me/swipe',
    summary: 'Record swipe event',
    description:
      'Inserts a `swipe` row after the client allows the action (quota is enforced on the client per design).',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: { target_user_id: '<other_user_uuid>', reaction: 'like' },
    responseExample: { success: true },
  },
  {
    id: 'ios.subscription.purchaseIntent',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/me/subscription/purchase-intent',
    summary: 'Start subscription purchase (CREATED)',
    description:
      'Creates a `subscription` row with status `CREATED` for the given `subscription_catalog_id` before StoreKit purchase.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: { subscription_catalog_id: '<catalog_uuid>' },
    responseExample: {
      subscription: {
        id: '<subscription_uuid>',
        status: 'CREATED',
        subscription_catalog_id: '<catalog_uuid>',
        created_at: '2026-04-04T12:00:00Z',
      },
    },
  },
  {
    id: 'ios.subscription.purchasing',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/me/subscription/{subscription_id}/purchasing',
    summary: 'Mark subscription PURCHASING',
    description:
      'Server-side transition `CREATED` → `PURCHASING` when StoreKit purchase is in progress. Use the UUID returned from purchase-intent.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {},
    responseExample: {
      subscription: {
        id: '<subscription_uuid>',
        status: 'PURCHASING',
        subscription_catalog_id: '<catalog_uuid>',
        original_transaction_id: null,
        environment: null,
      },
    },
  },
  {
    id: 'ios.subscription.status',
    audience: 'ios',
    method: 'GET',
    path: '/api/ios/me/subscription/status',
    summary: 'Poll subscription status',
    description:
      'Returns one subscription row for long-polling. Optional query `subscription_id`; if omitted, returns the latest row by `status_changed_at` / `updated_at`.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    params: [
      {
        name: 'subscription_id',
        in: 'query',
        required: false,
        description: 'When set, returns that row if it belongs to the authenticated user.',
        example: '<subscription_uuid>',
      },
    ],
    requestExample: {},
    responseExample: {
      subscription: {
        id: '<subscription_uuid>',
        status: 'ACTIVE',
        original_transaction_id: '<apple_original_txn>',
        environment: 'Production',
        current_period_start: '2026-04-01T00:00:00Z',
        current_period_end: '2026-05-01T00:00:00Z',
        auto_renew_status: true,
        status_changed_at: '2026-04-01T00:00:05Z',
        subscription_catalog_id: '<catalog_uuid>',
        subscription_catalog: {
          id: '<catalog_uuid>',
          apple_product_id: 'com.example.premium.monthly',
          name: 'Premium Monthly',
        },
      },
    },
  },
  {
    id: 'ios.posts.create',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/posts',
    summary: 'Create a post',
    description:
      'Create a new post. User ID is inferred from the token or can be passed.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {
      description: 'Visited Kyoto',
      location_name: 'Kyoto, Japan',
      longitude: 135.7681,
      latitude: 35.0116,
      occurred_at: '2025-01-01T00:00:00.000Z',
      photos: [],
    },
    responseExample: {
      id: '<post_uuid>',
      userid: '<user_uuid>',
      description: 'Visited Kyoto',
      location_name: 'Kyoto, Japan',
      occurred_at: '2025-01-01T00:00:00.000Z',
      photos: [],
      // ...
    },
  },
  {
    id: 'ios.posts.photos.upload',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/posts/<postid>/photos',
    summary: 'Upload photos to post',
    description:
      'Upload images to an existing post. Use multipart/form-data with key `files`. Appends to existing photos. Standard flow: Create Post -> Get ID -> Upload Photos.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: {
      Authorization: 'Bearer <AUTH_TOKEN>',
      // Content-Type is multipart/form-data, usually set automatically by client networking libs
    },
    requestExample: {
      _type: 'multipart/form-data',
      files: ['<file_bytes_1>', '<file_bytes_2>'],
    },
    responseExample: {
      success: true,
      photos: ['https://.../1.jpg', 'https://.../2.jpg'],
      added: ['https://.../2.jpg'],
    },
  },
  {
    id: 'ios.posts.list',
    audience: 'ios',
    method: 'GET',
    path: '/api/ios/users/<userid>/posts?startIndex=0&limit=5&hasLocation=false',
    summary: 'List user posts',
    description: 'Fetch posts for a user with pagination.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    params: [
      {
        name: 'startIndex',
        in: 'query',
        required: false,
        example: '0',
      },
      {
        name: 'limit',
        in: 'query',
        required: false,
        example: '5',
      },
      {
        name: 'hasLocation',
        in: 'query',
        required: false,
        example: 'false',
      },
    ],
    responseExample: [
      {
        id: '<post_uuid>',
        userid: '<user_uuid>',
        description: 'Post description',
        photos: ['url1', 'url2'],
        location_name: 'City',
        longitude: 100.0,
        latitude: 20.0,
        altitude: 10.0,
        occurred_at: '2025-01-01T00:00:00Z',
        created_at: '2025-01-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'ios.posts.delete',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_delete_post',
    summary: 'Delete a post (soft delete)',
    description:
      'Soft-deletes a post by setting user_posts.deleted_at = now(). Only the post owner (auth.uid()) can delete.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { post_id: '<post_uuid>' },
    responseExample: null, // void
  },
  {
    id: 'ios.earth.locations',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/locations',
    summary: 'Get Earth points',
    description: 'Fetch lightweight location data for 3D Earth view for multiple users.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {
      userIds: ['<user_uuid_1>', '<user_uuid_2>'],
      startIndex: 0,
      limit: 200,
    },
    responseExample: [
      {
        post_id: '<post_uuid>',
        userid: '<user_uuid>',
        occurred_at: '2025-01-01T00:00:00Z',
        longitude: 100.0,
        latitude: 20.0,
        altitude: 10.0,
        location_name: 'City',
        photos: ['https://example.com/photo1.jpg', 'https://example.com/photo2.jpg'],
      },
    ],
  },
  // RPCs for matching still use direct Supabase RPCs for now as they are "actions"
  // but we can wrap them if requested. For now, user complained about GET filters.
  {
    id: 'ios.match.send',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_send_match_request',
    summary: 'Send match request',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { target_user_id: '<other_user_uuid>' },
    responseExample: '<request_uuid_or_match_uuid>',
  },
  {
    id: 'ios.match.requests.list',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_list_match_requests',
    summary: 'List match requests (inbound/outbound)',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { direction: 'inbound', start_index: 0, limit_count: 20 },
    responseExample: [
      {
        request_id: '<request_uuid>',
        from_user_id: '<sender_uuid>',
        to_user_id: '<receiver_uuid>',
        created_at: '2025-01-01T00:00:00Z',
        other_user_id: '<other_uuid>',
        other_username: 'Bob',
        other_avatar: 'https://example.com/bob.jpg',
      },
    ],
  },
  {
    id: 'ios.match.accept',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_accept_match_request',
    summary: 'Accept match request',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { request_id: '<request_uuid>' },
    responseExample: null, // void
  },
  {
    id: 'ios.match.decline',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_decline_match_request',
    summary: 'Decline match request',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { request_id: '<request_uuid>' },
    responseExample: null, // void
  },
  {
    id: 'ios.match.cancel',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_cancel_match_request',
    summary: 'Cancel match request',
    description:
      'Sender cancels an outbound match request (deletes the request row).',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { request_id: '<request_uuid>' },
    responseExample: null, // void
  },
  {
    id: 'ios.connections.list',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_list_connections',
    summary: 'List connections',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { start_index: 0, limit_count: 50 },
    notes: [
      'Returns only the other participant profile fields (connection_*) plus `is_new_connection` which is true when there are no messages yet for the match_id.',
    ],
    responseExample: [
      {
        id: '<match_uuid>',
        connection_username: 'Bob',
        connection_user_id: '<bob_uuid>',
        connection_avatar: 'https://example.com/bob.jpg',
        created_at: '2025-01-01T00:00:00Z',
        is_new_connection: true,
      },
    ],
  },
  {
    id: 'ios.reports.user',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_report_user',
    summary: 'Report a user',
    description:
      'Creates a report row with target_user_id set and target_post_id = null.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { target_user_id: '<other_user_uuid>', reason: 'Spam' },
    responseExample: '<report_uuid>',
  },
  {
    id: 'ios.reports.post',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_report_post',
    summary: 'Report a post',
    description:
      'Creates a report row with both target_user_id and target_post_id set.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: {
      target_user_id: '<post_owner_user_uuid>',
      target_post_id: '<post_uuid>',
      reason: 'Inappropriate content',
    },
    responseExample: '<report_uuid>',
  },
  {
    id: 'ios.blocks.user',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_block_user',
    summary: 'Block a user',
    description:
      'Creates a block row (blocker_id = auth.uid(), blocked_id = target_user_id), cancels any pending requests between the two users, and clears AI state for the pair. Messages are preserved.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { target_user_id: '<other_user_uuid>' },
    responseExample: null, // void
  },
  {
    id: 'ios.blocks.user.unblock',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_unblock_user',
    summary: 'Unblock a user',
    description:
      'Removes the block row and ensures a match + ai_state exist again for the two users. Returns the match_id.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { target_user_id: '<other_user_uuid>' },
    responseExample: '<match_uuid>',
  },
  {
    id: 'ios.blocks.list',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_get_blocking_list',
    summary: 'Get blocking list',
    description: 'Lists users that the authenticated user has blocked.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: { start_index: 0, limit_count: 50 },
    responseExample: [
      {
        blocked_id: '<user_uuid>',
        blocked_username: 'Bob',
        blocked_avatar: 'https://example.com/bob.jpg',
        created_at: '2025-01-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'ios.matchings.feed',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/getMatchings',
    summary: 'Get matchings feed (swipe cards)',
    description:
      'Returns a swipe-card-ready list of candidate users for the authenticated user (userid derived from JWT). Avatar is used as the first image; postImages are taken from the user_posts photos arrays in order until image_count is reached. When gender_filter is provided, only users with that exact gender value are returned; leave it empty to use the default matching logic.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {
      count: 20,
      image_count: 7,
      gender_filter: 'Female',
    },
    responseExample: [
      {
        userId: '<candidate_uuid>',
        avatar: 'https://example.com/avatar.jpg',
        username: 'Alice',
        age: 28,
        gender: 'Female',
        bio: 'Hello',
        profession: 'Designer',
        postImages: [
          'https://example.com/p1.jpg',
          'https://example.com/p2.jpg',
        ],
      },
    ],
  },
  {
    id: 'ios.nearby.people.find',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/find-nearby-people',
    summary: 'Find nearby people + POIs',
    description:
      'Returns unmatched digital-human candidate profiles for the authenticated user and pairs each profile with a nearby real-world POI coordinate from Mapbox search around the provided location. When gender_filter is provided, only users with that exact gender value are returned; leave it empty to use the default nearby logic.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    params: [
      {
        name: 'longitude',
        in: 'body',
        required: true,
        description: 'User longitude used as Mapbox search proximity origin.',
        example: 139.6917,
      },
      {
        name: 'latitude',
        in: 'body',
        required: true,
        description: 'User latitude used as Mapbox search proximity origin.',
        example: 35.6895,
      },
      {
        name: 'gender_filter',
        in: 'body',
        required: false,
        description: 'Optional exact gender filter, for example "Female" or "Male". Empty or omitted means no gender filter.',
        example: 'Female',
      },
    ],
    requestExample: {
      longitude: 139.6917,
      latitude: 35.6895,
      gender_filter: 'Female',
    },
    responseExample: [
      {
        userId: '<candidate_uuid>',
        avatar: 'https://example.com/avatar.jpg',
        username: 'Alice',
        age: 28,
        gender: 'Female',
        bio: 'Hello',
        profession: 'Designer',
        postImages: ['https://example.com/p1.jpg'],
        longitude: 139.7001,
        latitude: 35.6922,
        distanceMiles: 0.53,
      },
    ],
  },
  {
    id: 'ios.storage.avatar.note',
    audience: 'ios',
    method: 'POST',
    path: '/storage/v1/object/images/<auth_uid>/avatar_<random>.jpg',
    summary: 'Upload avatar (Storage path convention)',
    description:
      'Upload to Storage under your folder (<auth_uid>/...). Then PATCH /api/ios/users/<userid> to set `avatar` = public URL.',
    auth: {
      type: 'bearer',
      notes:
        'For Storage uploads, include apikey + Authorization, and send the file bytes.',
    },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: {
      apikey: SUPABASE_ANON_KEY,
      Authorization: 'Bearer <AUTH_TOKEN>',
      'Content-Type': 'image/jpeg',
    },
    notes: [
      'Bucket is public for MVP: anyone with the URL can view the image.',
      'Write policy restricts uploads to paths starting with <auth_uid>/.',
    ],
    responseExample: {
      Key: 'images/<user_id>/avatar_xyz.jpg',
      // ... storage metadata
    },
  },
  {
    id: 'ios.chat.messages.list',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_get_messages',
    summary: 'Get Chat History',
    description: 'Fetch previous messages for a specific match.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: {
      match_id: '<match_uuid>',
      start_index: 0,
      limit_count: 50,
    },
    responseExample: [
      {
        id: '<message_uuid>',
        match_id: '<match_uuid>',
        sender_id: '<sender_uuid>',
        receiver_id: '<receiver_uuid>',
        content: 'Hello world',
        media_url: null,
        created_at: '2025-01-01T12:00:00Z',
      },
    ],
  },
  {
    id: 'ios.chat.messages.send',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/chat/send',
    summary: 'Send Message',
    description:
      'Send a message to a match. This is a Next.js API wrapper around rpc_send_message to bypass iOS HTTP/2 keep-alive connection drop issues.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: nextApiHeaders,
    requestExample: {
      match_id: '<match_uuid>',
      content: 'Hello world',
      media_url: null,
    },
    responseExample: {
      id: '<message_uuid>',
      match_id: '<match_uuid>',
      sender_id: '<sender_uuid>',
      receiver_id: '<receiver_uuid>',
      content: 'Hello world',
      media_url: null,
      created_at: '2025-01-01T12:00:00Z',
    },
  },
  {
    id: 'ios.chat.media.upload',
    audience: 'ios',
    method: 'POST',
    path: '/api/ios/chat/media',
    summary: 'Upload chat media',
    description:
      'Upload an image to chat_media bucket for a specific match. Use multipart/form-data with key `files`. Returns a public url to be used as `media_url` in Send Message.',
    auth: { type: 'bearer' },
    baseUrlOverride: APP_URL,
    defaultHeaders: {
      Authorization: 'Bearer <AUTH_TOKEN>',
      // Content-Type is multipart/form-data
    },
    requestExample: {
      _type: 'multipart/form-data',
      files: '<file_bytes>',
      match_id: '<match_uuid>',
    },
    responseExample: {
      media_url: 'https://...',
      path: '<match_uuid>/<filename>.jpg',
    },
  },
  {
    id: 'ios.chat.connections.metas',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/rpc/rpc_fetch_connections_chat_metas',
    summary: 'Fetch chat metadata (last msg + unread count)',
    description:
      'Fetch the most recent message and unread count for a list of matches. `unread_count` logic: if `last_read_time` is provided, counts messages after it. If not, counts messages after the last message sent by the current user.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: {
      params: [
        { match_id: '<match_uuid_1>' },
        { match_id: '<match_uuid_2>', last_read_time: '2025-01-01T12:00:00Z' },
      ],
    },
    responseExample: [
      {
        match_id: '<match_uuid>',
        message: 'Last message content',
        created_at: '2025-01-01T12:05:00Z',
        sender_id: '<sender_uuid>',
        receiver_id: '<receiver_uuid>',
        unread_count: 3,
        media_url: null,
        message_id: '<message_uuid>',
      },
    ],
  },
  {
    id: 'ios.reviews.appStore.template',
    audience: 'ios',
    method: 'GET',
    path: '/api/ios/reviews/app-store-template',
    summary: 'Generate a 5-star App Store review template',
    description:
      'Returns a freshly generated 5-star App Store review template for Amber. Every call produces a different compliment — the server assembles a unique prompt from randomly sampled dimensions (theme, tone, length, reviewer persona, uniqueness seed) before asking Gemini. If Gemini is unavailable or the response cannot be parsed, a randomly chosen local fallback template is returned instead. Intended for use as pre-fill text the user can tap to copy before leaving a real App Store review — never auto-submitted.',
    auth: {
      type: 'none',
      notes:
        'Currently unauthenticated (no user data is read or written). Add auth if you want to restrict who can generate templates.',
    },
    baseUrlOverride: APP_URL,
    defaultHeaders: {
      'Content-Type': 'application/json',
    },
    requestExample: {},
    responseExample: {
      rating: 5,
      title: 'Met my person on Amber',
      body: "I'd almost given up on dating apps when I tried this one. A few weeks in I met someone who genuinely gets me — can't recommend it enough.",
      source: 'gemini',
      generated_at: '2026-04-20T12:00:00.000Z',
    },
    notes: [
      '`source` is `"gemini"` for model-generated reviews and `"fallback"` when a local template was used.',
      'Response is always `Cache-Control: no-store` so every call yields a fresh review.',
      'Always returns rating = 5 (this is a 5-star template generator only).',
      'Do NOT auto-submit this text to App Store Connect — show it to the user and let them edit/submit.',
    ],
  },
  {
    id: 'ios.push.tokens.register',
    audience: 'ios',
    method: 'POST',
    path: '/rest/v1/user_push_tokens',
    summary: 'Register FCM/APNs Token',
    description: 'Register device token for push notifications.',
    auth: { type: 'bearer' },
    baseUrlOverride: SUPABASE_URL,
    defaultHeaders: supabaseAuthHeaders,
    requestExample: {
      user_id: '<auth_uid>',
      token: '<fcm_token>',
      platform: 'ios',
    },
    responseExample: null, // void or row
  },
];
